In [2]:
import boto3
import pandas as pd

#INGESTING PRODUCTS DATA INTO PRODUCTS
s3_client = boto3.client("s3")
BUCKET='etoilecinema'
KEY='moviere/moviere.csv'

response = s3_client.get_object(Bucket=BUCKET, Key=KEY)
moviere = pd.read_csv(response.get("Body"))
moviere.head(3)

,Int,Rank_data,PreviousWeekRank,Metascore,Meta_Pos_Count,Meta_Neut_Count,Meta_Neg_Count,User_Score,User_Pos_Count,User_Neut_Count,User_Neg_Count,MovieName,GrossW,Publisher,Runtime,Summary,Director,Starring,Genre,Rating
0,0,1,1,61,22,7,3,6.8,0,0,0,Stuart Little,13012299,American Broadcasting Company (ABC),84 min,The adventures of a heroic and debonair stalwa...,Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.
1,1,2,1,61,22,7,3,6.8,0,0,0,Stuart Little,13560203,American Broadcasting Company (ABC),84 min,The adventures of a heroic and debonair stalwa...,Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.
2,2,4,2,61,22,7,3,6.8,0,0,0,Stuart Little,7554094,American Broadcasting Company (ABC),84 min,The adventures of a heroic and debonair stalwa...,Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.

In [3]:
##################### DATA CLEANING ##################################
#Drop the summary column as it is very bulky and not helpful to our model
moviere = moviere.drop(columns=['Summary'])
moviere.head(3)

,Int,Rank_data,PreviousWeekRank,Metascore,Meta_Pos_Count,Meta_Neut_Count,Meta_Neg_Count,User_Score,User_Pos_Count,User_Neut_Count,User_Neg_Count,MovieName,GrossW,Publisher,Runtime,Director,Starring,Genre,Rating
0,0,1,1,61,22,7,3,6.8,0,0,0,Stuart Little,13012299,American Broadcasting Company (ABC),84 min,Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.
1,1,2,1,61,22,7,3,6.8,0,0,0,Stuart Little,13560203,American Broadcasting Company (ABC),84 min,Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.
2,2,4,2,61,22,7,3,6.8,0,0,0,Stuart Little,7554094,American Broadcasting Company (ABC),84 min,Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.

In [4]:
# Drop min from run time
Runtime_Value = list()
for i in moviere["Runtime"]:
    if " " in i:
        split = i.split()
        Runtime_Value.append(split[0])
    else:
        Runtime_Value.append(i)

moviere["Runtime_Value"]=Runtime_Value
moviere.head(3)

,Int,Rank_data,PreviousWeekRank,Metascore,Meta_Pos_Count,Meta_Neut_Count,Meta_Neg_Count,User_Score,User_Pos_Count,User_Neut_Count,User_Neg_Count,MovieName,GrossW,Publisher,Runtime,Director,Starring,Genre,Rating,Runtime_Value
0,0,1,1,61,22,7,3,6.8,0,0,0,Stuart Little,13012299,American Broadcasting Company (ABC),84 min,Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.,84
1,1,2,1,61,22,7,3,6.8,0,0,0,Stuart Little,13560203,American Broadcasting Company (ABC),84 min,Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.,84
2,2,4,2,61,22,7,3,6.8,0,0,0,Stuart Little,7554094,American Broadcasting Company (ABC),84 min,Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.,84

In [5]:
#Drop the original runtime column
moviere = moviere.drop(columns=['Runtime'])
moviere.head(3)

,Int,Rank_data,PreviousWeekRank,Metascore,Meta_Pos_Count,Meta_Neut_Count,Meta_Neg_Count,User_Score,User_Pos_Count,User_Neut_Count,User_Neg_Count,MovieName,GrossW,Publisher,Director,Starring,Genre,Rating,Runtime_Value
0,0,1,1,61,22,7,3,6.8,0,0,0,Stuart Little,13012299,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.,84
1,1,2,1,61,22,7,3,6.8,0,0,0,Stuart Little,13560203,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.,84
2,2,4,2,61,22,7,3,6.8,0,0,0,Stuart Little,7554094,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.,84

In [7]:
#We need to change the rating column to only show the rating. 
#Some rows already do this but many have extraneous info
moviere["Rated"] =""

for idx, val in enumerate(moviere["Rating"]):
    rating = str(val)
    
    if len(rating) >= 15:
        rating = rating[0:15]
    
    if " " not in rating: 
        moviere.loc[idx, 'Rated'] = rating
    elif " PG " in rating: 
        moviere.loc[idx, 'Rated'] ="PG"
    elif " PG" in rating and "13 " in rating: 
        moviere.loc[idx, 'Rated'] = "PG-13"
    elif " R " in rating: 
        moviere.loc[idx, 'Rated'] = "R"
    elif " G " in rating: 
        moviere.loc[idx, 'Rated'] = "G"
    elif rating == "NR" or rating == "Not Rated": 
        moviere.loc[idx, 'Rated'] = "NR"
    elif "NC-17" in rating: 
        moviere.loc[idx, 'Rated'] = "NC-17"
    else: 
        moviere.loc[idx, 'Rated'] = "Unknown"

moviere.head(3)

,Int,Rank_data,PreviousWeekRank,Metascore,Meta_Pos_Count,Meta_Neut_Count,Meta_Neg_Count,User_Score,User_Pos_Count,User_Neut_Count,User_Neg_Count,MovieName,GrossW,Publisher,Director,Starring,Genre,Rating,Runtime_Value,Rated
0,0,1,1,61,22,7,3,6.8,0,0,0,Stuart Little,13012299,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.,84,PG
1,1,2,1,61,22,7,3,6.8,0,0,0,Stuart Little,13560203,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.,84,PG
2,2,4,2,61,22,7,3,6.8,0,0,0,Stuart Little,7554094,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,Rated PG for brief language.,84,PG

In [8]:
#Checking missing values after combining
moviere.isna().sum()

Int                 0
Rank_data           0
PreviousWeekRank    0
Metascore           0
Meta_Pos_Count      0
Meta_Neut_Count     0
Meta_Neg_Count      0
User_Score          0
User_Pos_Count      0
User_Neut_Count     0
User_Neg_Count      0
MovieName           0
GrossW              0
Publisher           0
Director            0
Starring            0
Genre               0
Rating              0
Runtime_Value       0
Rated               0
dtype: int64

In [9]:
#Drop the original rating column
moviere = moviere.drop(columns=['Rating'])
moviere.head(3)

,Int,Rank_data,PreviousWeekRank,Metascore,Meta_Pos_Count,Meta_Neut_Count,Meta_Neg_Count,User_Score,User_Pos_Count,User_Neut_Count,User_Neg_Count,MovieName,GrossW,Publisher,Director,Starring,Genre,Runtime_Value,Rated
0,0,1,1,61,22,7,3,6.8,0,0,0,Stuart Little,13012299,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,84,PG
1,1,2,1,61,22,7,3,6.8,0,0,0,Stuart Little,13560203,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,84,PG
2,2,4,2,61,22,7,3,6.8,0,0,0,Stuart Little,7554094,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,84,PG

In [10]:
########################### Importing to Athena ####################
#Locating the S3 bucket
!aws s3 ls s3://etoilecinema/moviere/

2022-03-27 15:48:32          0
2022-03-27 16:01:33   58768169 moviere.csv

In [11]:
import boto3
import sagemaker
import pandas as pd

sess = sagemaker.Session()
bucket = sess.default_bucket()
role = sagemaker.get_execution_role()
region = boto3.Session().region_name
account_id = boto3.client("sts").get_caller_identity().get("Account")
sm = boto3.Session().client(service_name="sagemaker", region_name=region)

In [12]:
#SET S3 SOURCE LOCATION (PUBLIC S3 BUCKET)
s3_public_path_csv = "s3://etoilecinema"
%store s3_public_path_csv

Stored 's3_public_path_csv' (str)

In [13]:
#SET S3 DESTINATION LOCATION (PRIVATE S3 BUCKET)
s3_private_path_csv = "s3://{}/etoilecinema".format(bucket)
print(s3_private_path_csv)

s3://sagemaker-us-east-1-105521790034/etoilecinema

In [14]:
#COPY DATA FROM PUBLIC BUCKET S3 TO OUR PRIVATE S3 BUCKET
!aws s3 cp --recursive $s3_public_path_csv/ $s3_private_path_csv/ --exclude "*" --include "moviere/moviere.csv"

copy: s3://etoilecinema/moviere/moviere.csv to s3://sagemaker-us-east-1-105521790034/etoilecinema/moviere/moviere.csv

In [15]:
print(s3_private_path_csv)

s3://sagemaker-us-east-1-105521790034/etoilecinema

In [16]:
!aws s3 ls $s3_private_path_csv/moviere/

2022-03-27 19:12:55   58768169 moviere.csv

In [17]:
!pip install --disable-pip-version-check -q PyAthena==2.1.0
from pyathena import connect

/opt/conda/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [18]:
# Set S3 staging directory -- this is a temporary directory used for Athena queries
s3_private_path_moviere= "s3://{}/etoilecinema/moviere/".format(bucket)
print(s3_private_path_moviere)

s3://sagemaker-us-east-1-105521790034/etoilecinema/moviere/

In [19]:
s3_staging_dir = "s3://{0}/athena/staging".format(bucket)
conn = connect(region_name=region, s3_staging_dir=s3_staging_dir)

In [20]:
#Checking if database named nnoo is created or not
database_name = "etoilecinema"
statement = "CREATE DATABASE IF NOT EXISTS {}".format(database_name)
print(statement)
pd.read_sql(statement, conn)
statement = "SHOW DATABASES"
df_show = pd.read_sql(statement, conn)
df_show.head(15)

CREATE DATABASE IF NOT EXISTS etoilecinema

   database_name
0  critic_review
1        default
2         dsoaws
3        ecinema
4      ejcinemas
5         etoile
6   etoilecinema
7           nnoo

In [21]:
#SETTING UP ATHENA PARAMETERS
moviere_table = "moviere"

In [23]:
moviere.head(3)

,Int,Rank_data,PreviousWeekRank,Metascore,Meta_Pos_Count,Meta_Neut_Count,Meta_Neg_Count,User_Score,User_Pos_Count,User_Neut_Count,User_Neg_Count,MovieName,GrossW,Publisher,Director,Starring,Genre,Runtime_Value,Rated
0,0,1,1,61,22,7,3,6.8,0,0,0,Stuart Little,13012299,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,84,PG
1,1,2,1,61,22,7,3,6.8,0,0,0,Stuart Little,13560203,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,84,PG
2,2,4,2,61,22,7,3,6.8,0,0,0,Stuart Little,7554094,American Broadcasting Company (ABC),Rob Minkoff,"Geena Davis, Michael J. Fox, Allyce Beasley, B...",Adventure;Fantasy;Comedy;Family,84,PG

In [24]:
#SQL STATEMENT FOR CINEMAS TABLE
statement_moviere = """CREATE EXTERNAL TABLE IF NOT EXISTS {}.{}(
 Int int,
 Rank_data int,
 PreviousWeekRank float,
 Metascore int,
 Meta_Pos_Count int,
 Meta_Neut_Count int,
 Meta_Neg_Count int,
 User_Score float,
 User_Pos_Count int,
 User_Neut_Count int,
 User_Neg_Count int,
 MovieName string,
 GrossW int,
 Publisher string,
 Director string,
 Starring string,
 Genre string,
 Runtime_Value int,
 Rated string
)

ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'
LOCATION '{}'
TBLPROPERTIES ('skip.header.line.count'='1')""".format(
database_name, moviere_table, s3_private_path_moviere)

pd.read_sql(statement_moviere, conn)

Empty DataFrame
Columns: []
Index: []

In [26]:
statement = """SELECT * FROM {}.{}
 """.format(database_name, moviere_table)
print(statement)

df = pd.read_sql(statement, conn)
df.head()

SELECT * FROM etoilecinema.moviere

,int,rank_data,previousweekrank,metascore,meta_pos_count,meta_neut_count,meta_neg_count,user_score,user_pos_count,user_neut_count,user_neg_count,moviename,grossw,publisher,runtime,summary,director,starring,genre,rating
0,0.0,1.0,1.0,61.0,22.0,7.0,3.0,6.8,0.0,0.0,0.0,Stuart Little,13012299.0,American Broadcasting Company (ABC),84 min,"""The adventures of a heroic and debonair stalw...",who faces some comic misadventures while sear...,Rob Minkoff,"""Geena Davis",Michael J. Fox
1,1.0,2.0,1.0,61.0,22.0,7.0,3.0,6.8,0.0,0.0,0.0,Stuart Little,13560203.0,American Broadcasting Company (ABC),84 min,"""The adventures of a heroic and debonair stalw...",who faces some comic misadventures while sear...,Rob Minkoff,"""Geena Davis",Michael J. Fox
2,2.0,4.0,2.0,61.0,22.0,7.0,3.0,6.8,0.0,0.0,0.0,Stuart Little,7554094.0,American Broadcasting Company (ABC),84 min,"""The adventures of a heroic and debonair stalw...",who faces some comic misadventures while sear...,Rob Minkoff,"""Geena Davis",Michael J. Fox
3,3.0,4.0,4.0,61.0,22.0,7.0,3.0,6.8,0.0,0.0,0.0,Stuart Little,5690856.0,American Broadcasting Company (ABC),84 min,"""The adventures of a heroic and debonair stalw...",who faces some comic misadventures while sear...,Rob Minkoff,"""Geena Davis",Michael J. Fox
4,4.0,3.0,4.0,61.0,22.0,7.0,3.0,6.8,0.0,0.0,0.0,Stuart Little,5394977.0,American Broadcasting Company (ABC),84 min,"""The adventures of a heroic and debonair stalw...",who faces some comic misadventures while sear...,Rob Minkoff,"""Geena Davis",Michael J. Fox

In [27]:
#CHECKING TOP TEN MOVIENAME WITH METASCORE
statement = ""
statement = """SELECT MovieName, max(metascore) as Max_Metascore FROM
{}.{}
 group by MovieName
 order by Max_Metascore desc
 """.format(
 database_name, moviere_table
)
print(statement)
df = pd.read_sql(statement, conn)
df.head(10)

SELECT MovieName, max(metascore) as Max_Metascore FROM
etoilecinema.moviere
 group by MovieName
 order by Max_Metascore desc

                    MovieName  Max_Metascore
0                     Boyhood          100.0
1                   Moonlight           99.0
2       Manchester by the Sea           96.0
3                    Parasite           96.0
4  Portrait of a Lady on Fire           95.0
5                A Separation           95.0
6          The Social Network           95.0
7                  La La Land           94.0
8                    45 Years           94.0
9                Faces Places           94.0

In [ ]:
########################### Training ##############################